version: 2

sources:
  - name: raw_store
    schema: raw_store  
    tables:
      - name: raw_gme
      - name: raw_amzn
      - name: raw_ffie
      - name: raw_aapl
      - name: raw_msft
      - name: raw_googl
      - name: raw_meta